<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * QrRegistration Model
 *
 * Represents a student or staff member who has been registered for
 * QR-based attendance.  Each row holds the person's identity info
 * and a single permanent qr_token (UUID) that is encoded inside
 * their QR image.
 *
 * One school_id  → one permanent QR token (enforced by the unique
 * constraint on both school_id and qr_token).
 *
 * qr_generated_at tracks when the token was first created (or last
 * regenerated by an administrator).
 */
class QrRegistration extends Model
{
    /** The database table for QR-registered users. */
    protected $table = 'qr_registrations';

    /**
     * Enable standard Laravel timestamps (created_at / updated_at).
     * Unlike rfid_cards, this table uses the two-column convention so
     * we can track when a record was originally created vs. last edited.
     */
    public $timestamps = true;

    /**
     * Mass-assignable columns.
     * qr_generated_at is included so it can be explicitly set when a
     * token is regenerated by an admin.
     * id and timestamps are intentionally excluded.
     */
    protected $fillable = [
        'school_id',        // normalised school / employee ID
        'last_name',
        'first_name',
        'middle_initial',
        'qr_token',         // UUID encoded inside the QR image
        'qr_generated_at',  // when the current token was issued
    ];

    /**
     * Column type casts.
     * qr_generated_at is cast to Carbon so it renders nicely when
     * serialised to JSON (e.g. "2024-05-01T08:00:00.000000Z").
     */
    protected $casts = [
        'qr_generated_at' => 'datetime',
        'created_at'      => 'datetime',
        'updated_at'      => 'datetime',
    ];
}
